apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-pod.fullname" . }}
  labels:
    app: {{ include "demo-pod.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "demo-pod.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "demo-pod.name" . }}
    spec:
      serviceAccountName: {{ if .Values.serviceAccount.create }}{{ include "demo-pod.serviceAccountName" . }}{{ else }}default{{ end }}
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
